[build]
  publish = "build/web"
  command = "flutter build web --web-renderer canvaskit --release --dart-define=APP_ENV=production"

[build.environment]
  FLUTTER_VERSION = "3.24.0"
  DART_VERSION = "3.5.0"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy rules
[[redirects]]
  from = "/api/*"
  to = "https://api.alpaca.markets/:splat"
  status = 200
  force = false

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = '''
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data: https:;
      connect-src 'self' https://api.alpaca.markets https://paper-api.alpaca.markets wss://stream.data.alpaca.markets https://*.supabase.co wss://*.supabase.co https://www.googleapis.com https://www.google-analytics.com;
      frame-ancestors 'none';
      base-uri 'self';
      form-action 'self';
    '''

# Cache optimization for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Edge functions for performance
[[edge_functions]]
  function = "performance-monitor"
  path = "/*"

# Form handling
[[forms]]
  name = "contact"
  action = "/thank-you"

# Environment variables (use Netlify dashboard to set actual values)
[context.production.environment]
  NODE_ENV = "production"
  APP_ENV = "production"
  FLUTTER_WEB_CANVASKIT_URL = "https://unpkg.com/canvaskit-wasm@0.39.1/bin/"

[context.deploy-preview.environment]
  NODE_ENV = "staging"
  APP_ENV = "staging"

[context.branch-deploy.environment]
  NODE_ENV = "development"
  APP_ENV = "development"

# Plugin configurations
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs]
    output_path = "reports/lighthouse"
    audit_url = "https://pulse-trading.com"

[[plugins]]
  package = "netlify-plugin-checklinks"

[[plugins]]
  package = "@netlify/plugin-sitemap"

# Split testing
[split_testing]
  [split_testing.experiments.performance_optimization]
    bucket_by = "cookie"
    variants = ["original", "optimized"]